-------------------------------------------------------------------------------
Test set: pl.pandait.panda.PandaApplicationSeleniumTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.793 sec <<< FAILURE! - in pl.pandait.panda.PandaApplicationSeleniumTest
pl.pandait.panda.PandaApplicationSeleniumTest  Time elapsed: 9.792 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: 
Reached error page: about:neterror?e=connectionFailure&u=http%3A//10.0.2.15%3A8080/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2010.0.2.15%3A8080.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'pandabox2', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-46-generic', java.version: '11.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 74.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200309095159, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 77, moz:profile: /tmp/rust_mozprofileZVTNpe, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.3.0-46-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 07396d54-d008-432b-9201-fbe...}
Session ID: 07396d54-d008-432b-9201-fbea418e379b
	at pl.pandait.panda.PandaApplicationSeleniumTest.startup(PandaApplicationSeleniumTest.java:35)

